[tool.poetry]
name = "kyo-django-tutorial"
version = "0.1.0"
description = ""
authors = ["kyo <odinxp@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "kyo_django_tutorial"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
