# Generated by Django 4.2.2 on 2023-06-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='post', to='post.title'
            ),
        ),
    ]
